//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.NuGet.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.NuGet.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllNodeName {
            get {
                return ResourceManager.GetString("AllNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckedImage {
            get {
                object obj = ResourceManager.GetObject("CheckedImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing package metadata file exists. Do you want to create a new file?.
        /// </summary>
        internal static string CreatePackageMetadata {
            get {
                return ResourceManager.GetString("CreatePackageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each item above may have sub-dependencies subject to additional license agreements..
        /// </summary>
        internal static string DependencyLicenseWarningLabel {
            get {
                return ResourceManager.GetString("DependencyLicenseWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownloadImage {
            get {
                object obj = ResourceManager.GetObject("DownloadImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string ExportOperationLabel {
            get {
                return ResourceManager.GetString("ExportOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string FailedOperationLabel {
            get {
                return ResourceManager.GetString("FailedOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed packages.
        /// </summary>
        internal static string InstalledPackagesNodeName {
            get {
                return ResourceManager.GetString("InstalledPackagesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable package.
        /// </summary>
        internal static string InstallExecutablePackageCaption {
            get {
                return ResourceManager.GetString("InstallExecutablePackageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; is an executable package. Do you want to open the workflow?.
        /// </summary>
        internal static string InstallExecutablePackageWarning {
            get {
                return ResourceManager.GetString("InstallExecutablePackageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string InstallOperationLabel {
            get {
                return ResourceManager.GetString("InstallOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos;..
        /// </summary>
        internal static string InstallPackageLatestVersion {
            get {
                return ResourceManager.GetString("InstallPackageLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0} {1}&apos;..
        /// </summary>
        internal static string InstallPackageVersion {
            get {
                return ResourceManager.GetString("InstallPackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; is not a gallery package. Please install this package through the package manager dialog..
        /// </summary>
        internal static string InvalidGalleryPackage {
            get {
                return ResourceManager.GetString("InvalidGalleryPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Author: {0}).
        /// </summary>
        internal static string LicenseAuthorshipLabel {
            get {
                return ResourceManager.GetString("LicenseAuthorshipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LicenseImage {
            get {
                object obj = ResourceManager.GetObject("LicenseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License.
        /// </summary>
        internal static string LicenseViewLicenseLabel {
            get {
                return ResourceManager.GetString("LicenseViewLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string MissingPackageLatestVersion {
            get {
                return ResourceManager.GetString("MissingPackageLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0} {1}&apos; could not be found..
        /// </summary>
        internal static string MissingPackageVersion {
            get {
                return ResourceManager.GetString("MissingPackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open gallery package. No &apos;{0}&apos; was found in package contents..
        /// </summary>
        internal static string MissingWorkflowEntryPoint {
            get {
                return ResourceManager.GetString("MissingWorkflowEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple updates available..
        /// </summary>
        internal static string MultipleUpdatesLabel {
            get {
                return ResourceManager.GetString("MultipleUpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        internal static string MultipleUpdatesOperationName {
            get {
                return ResourceManager.GetString("MultipleUpdatesOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dependencies.
        /// </summary>
        internal static string NoDependenciesLabel {
            get {
                return ResourceManager.GetString("NoDependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        internal static string NoItemsFoundLabel {
            get {
                return ResourceManager.GetString("NoItemsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package updates are available..
        /// </summary>
        internal static string NoUpdatesAvailableLabel {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string OnlineNodeName {
            get {
                return ResourceManager.GetString("OnlineNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenImage {
            get {
                object obj = ResourceManager.GetObject("OpenImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already installed..
        /// </summary>
        internal static string PackageAlreadyInstalled {
            get {
                return ResourceManager.GetString("PackageAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageDefaultIcon {
            get {
                object obj = ResourceManager.GetObject("PackageDefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; depends on the following packages. Do you want to uninstall them too?
        ///.
        /// </summary>
        internal static string PackageDependencyNotice {
            get {
                return ResourceManager.GetString("PackageDependencyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Use | instead..
        /// </summary>
        internal static string PackageDeprecationAlternateNotice {
            get {
                return ResourceManager.GetString("PackageDeprecationAlternateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package has been deprecated as it is legacy and is no longer maintained..
        /// </summary>
        internal static string PackageDeprecationDefaultMessage {
            get {
                return ResourceManager.GetString("PackageDeprecationDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package version is deprecated..
        /// </summary>
        internal static string PackageDeprecationNotice {
            get {
                return ResourceManager.GetString("PackageDeprecationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0} {1}&apos; exported successfully..
        /// </summary>
        internal static string PackageExported {
            get {
                return ResourceManager.GetString("PackageExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageImage {
            get {
                object obj = ResourceManager.GetObject("PackageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageInstalledImage {
            get {
                object obj = ResourceManager.GetObject("PackageInstalledImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID prefix of this package has been reserved for the owner of the package by the currently selected feed.
        /// </summary>
        internal static string PackagePrefixReservedToolTip {
            get {
                return ResourceManager.GetString("PackagePrefixReservedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageRemoveImage {
            get {
                object obj = ResourceManager.GetObject("PackageRemoveImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageUpdateImage {
            get {
                object obj = ResourceManager.GetObject("PackageUpdateImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string PackageWarningKey {
            get {
                return ResourceManager.GetString("PackageWarningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrefixReservedImage {
            get {
                object obj = ResourceManager.GetObject("PrefixReservedImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrefixReservedMediumImage {
            get {
                object obj = ResourceManager.GetObject("PrefixReservedMediumImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerelease.
        /// </summary>
        internal static string PrereleaseLabel {
            get {
                return ResourceManager.GetString("PrereleaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshImage {
            get {
                object obj = ResourceManager.GetObject("RefreshImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring dependency &apos;{0} {1}&apos;..
        /// </summary>
        internal static string RestorePackageVersion {
            get {
                return ResourceManager.GetString("RestorePackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information....
        /// </summary>
        internal static string RetrievingInformationLabel {
            get {
                return ResourceManager.GetString("RetrievingInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &apos;{0}&apos; already exists. Please select a different folder name..
        /// </summary>
        internal static string SaveFolderExists {
            get {
                return ResourceManager.GetString("SaveFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location already exists.
        /// </summary>
        internal static string SaveFolderExistsCaption {
            get {
                return ResourceManager.GetString("SaveFolderExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package metadata has unsaved changes. Save metadata file?.
        /// </summary>
        internal static string SavePackageMetadata {
            get {
                return ResourceManager.GetString("SavePackageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Ctrl+L).
        /// </summary>
        internal static string SearchCueBanner {
            get {
                return ResourceManager.GetString("SearchCueBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsImage {
            get {
                object obj = ResourceManager.GetObject("SettingsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UncheckedImage {
            get {
                object obj = ResourceManager.GetObject("UncheckedImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string UninstallOperationLabel {
            get {
                return ResourceManager.GetString("UninstallOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unpublished).
        /// </summary>
        internal static string UnpublishedLabel {
            get {
                return ResourceManager.GetString("UnpublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string UpdateOperationLabel {
            get {
                return ResourceManager.GetString("UpdateOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string UpdatesNodeName {
            get {
                return ResourceManager.GetString("UpdatesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaitImage {
            get {
                object obj = ResourceManager.GetObject("WaitImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarningImage {
            get {
                object obj = ResourceManager.GetObject("WarningImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebImage {
            get {
                object obj = ResourceManager.GetObject("WebImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
