//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The Bonsai framework includes software from the NuGet Project developed at the Outercurve Foundation (http://www.outercurve.org/).
        ///
        ///Copyright 2010-2012 Outercurve Foundation.
        /// </summary>
        internal static string AttributionNotices {
            get {
                return ResourceManager.GetString("AttributionNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bonsai {
            get {
                object obj = ResourceManager.GetObject("Bonsai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BonsaiCommands {
            get {
                object obj = ResourceManager.GetObject("BonsaiCommands", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonsai.
        /// </summary>
        internal static string BonsaiTitle {
            get {
                return ResourceManager.GetString("BonsaiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BonsaiWelcome {
            get {
                object obj = ResourceManager.GetObject("BonsaiWelcome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ContextMenu_NoneVisualizerItemLabel {
            get {
                return ResourceManager.GetString("ContextMenu_NoneVisualizerItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error copying the selected elements to the clipboard:
        ///{0}.
        /// </summary>
        internal static string CopyToClipboard_Error {
            get {
                return ResourceManager.GetString("CopyToClipboard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Error.
        /// </summary>
        internal static string Editor_Error_Caption {
            get {
                return ResourceManager.GetString("Editor_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the Bonsai workflow:
        ///{0}.
        /// </summary>
        internal static string OpenWorkflow_Error {
            get {
                return ResourceManager.GetString("OpenWorkflow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error.
        /// </summary>
        internal static string OpenWorkflow_Error_Caption {
            get {
                return ResourceManager.GetString("OpenWorkflow_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error pasting the selected elements from the clipboard:
        ///{0}.
        /// </summary>
        internal static string PasteFromClipboard_Error {
            get {
                return ResourceManager.GetString("PasteFromClipboard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the Bonsai workflow:
        ///{0}.
        /// </summary>
        internal static string SaveWorkflow_Error {
            get {
                return ResourceManager.GetString("SaveWorkflow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.
        /// </summary>
        internal static string SaveWorkflow_Error_Caption {
            get {
                return ResourceManager.GetString("SaveWorkflow_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Modules (Ctrl+E).
        /// </summary>
        internal static string SearchModuleCueBanner {
            get {
                return ResourceManager.GetString("SearchModuleCueBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBlockedImage {
            get {
                object obj = ResourceManager.GetObject("StatusBlockedImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusCriticalImage {
            get {
                object obj = ResourceManager.GetObject("StatusCriticalImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusReadyImage {
            get {
                object obj = ResourceManager.GetObject("StatusReadyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
