//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The Bonsai framework includes software from the Reactive Extensions for .NET and the NuGet projects developed at the .NET Foundation (https://dotnetfoundation.org/).
        ///
        ///Copyright (c) .NET Foundation and Contributors.
        /// </summary>
        internal static string AttributionNotices {
            get {
                return ResourceManager.GetString("AttributionNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bonsai {
            get {
                object obj = ResourceManager.GetObject("Bonsai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonsai.
        /// </summary>
        internal static string BonsaiTitle {
            get {
                return ResourceManager.GetString("BonsaiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ContextMenu_NoneMenuItemLabel {
            get {
                return ResourceManager.GetString("ContextMenu_NoneMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error copying the selected elements to the clipboard:
        ///{0}.
        /// </summary>
        internal static string CopyToClipboard_Error {
            get {
                return ResourceManager.GetString("CopyToClipboard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions folder does not exist in the current working directory. Do you want to create it?.
        /// </summary>
        internal static string CreateExtensionsFolder_Question {
            get {
                return ResourceManager.GetString("CreateExtensionsFolder_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Extensions Folder.
        /// </summary>
        internal static string CreateExtensionsFolder_Question_Caption {
            get {
                return ResourceManager.GetString("CreateExtensionsFolder_Question_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow must be saved before adding new extensions..
        /// </summary>
        internal static string CreateExtensionsWorkflow_Warning {
            get {
                return ResourceManager.GetString("CreateExtensionsWorkflow_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workflow.
        /// </summary>
        internal static string CreateExtensionsWorkflow_Warning_Caption {
            get {
                return ResourceManager.GetString("CreateExtensionsWorkflow_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Error.
        /// </summary>
        internal static string Editor_Error_Caption {
            get {
                return ResourceManager.GetString("Editor_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting the target nodes in the specified order would create a loop in the workflow. Consider inserting the operator as a branch..
        /// </summary>
        internal static string InsertValidation_Error {
            get {
                return ResourceManager.GetString("InsertValidation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open script editor.
        ///Do you want to install Visual Studio Code?.
        /// </summary>
        internal static string InstallScriptEditor_Question {
            get {
                return ResourceManager.GetString("InstallScriptEditor_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Script Editor.
        /// </summary>
        internal static string InstallScriptEditor_Question_Caption {
            get {
                return ResourceManager.GetString("InstallScriptEditor_Question_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the Bonsai workflow:
        ///{0}.
        /// </summary>
        internal static string OpenWorkflow_Error {
            get {
                return ResourceManager.GetString("OpenWorkflow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error.
        /// </summary>
        internal static string OpenWorkflow_Error_Caption {
            get {
                return ResourceManager.GetString("OpenWorkflow_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package updates are available.
        /// </summary>
        internal static string PackageUpdatesAvailable_Notification {
            get {
                return ResourceManager.GetString("PackageUpdatesAvailable_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error pasting the selected elements from the clipboard:
        ///{0}.
        /// </summary>
        internal static string PasteFromClipboard_Error {
            get {
                return ResourceManager.GetString("PasteFromClipboard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; does not exist anymore. Do you want to remove the reference to it from the list of recent files?.
        /// </summary>
        internal static string RemoveRecentFile_Question {
            get {
                return ResourceManager.GetString("RemoveRecentFile_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonsai.
        /// </summary>
        internal static string RemoveRecentFile_Question_Caption {
            get {
                return ResourceManager.GetString("RemoveRecentFile_Question_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while reordering the selected nodes:
        ///{0}.
        /// </summary>
        internal static string ReorderGraphNodes_Error {
            get {
                return ResourceManager.GetString("ReorderGraphNodes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.
        /// </summary>
        internal static string SaveElement_Error_Caption {
            get {
                return ResourceManager.GetString("SaveElement_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the visualizer layout:
        ///{0}.
        /// </summary>
        internal static string SaveLayout_Error {
            get {
                return ResourceManager.GetString("SaveLayout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the Bonsai workflow:
        ///{0}.
        /// </summary>
        internal static string SaveWorkflow_Error {
            get {
                return ResourceManager.GetString("SaveWorkflow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Modules (Ctrl+E).
        /// </summary>
        internal static string SearchModuleCueBanner {
            get {
                return ResourceManager.GetString("SearchModuleCueBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBlockedImage {
            get {
                object obj = ResourceManager.GetObject("StatusBlockedImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusCriticalImage {
            get {
                object obj = ResourceManager.GetObject("StatusCriticalImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusReadyImage {
            get {
                object obj = ResourceManager.GetObject("StatusReadyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusRunningImage {
            get {
                object obj = ResourceManager.GetObject("StatusRunningImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusUpdateAvailable {
            get {
                object obj = ResourceManager.GetObject("StatusUpdateAvailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to evaluate uncompiled script expression. Please ensure all script files have been created and reload extensions..
        /// </summary>
        internal static string UncompiledScriptExpression_Error {
            get {
                return ResourceManager.GetString("UncompiledScriptExpression_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while updating the workflow. Please check if there are any missing packages that need to be installed before trying to upgrade again..
        /// </summary>
        internal static string UpdateWorkflow_Error {
            get {
                return ResourceManager.GetString("UpdateWorkflow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This workflow file has been created with an older version of Bonsai. Further modifications will be incompatible with previous versions..
        /// </summary>
        internal static string UpdateWorkflow_Warning {
            get {
                return ResourceManager.GetString("UpdateWorkflow_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Workflow.
        /// </summary>
        internal static string UpdateWorkflow_Warning_Caption {
            get {
                return ResourceManager.GetString("UpdateWorkflow_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externalized properties of this workflow can be configured below..
        /// </summary>
        internal static string WorkflowPropertiesDescription {
            get {
                return ResourceManager.GetString("WorkflowPropertiesDescription", resourceCulture);
            }
        }
    }
}
