//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Shaders.Configuration.Design {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Shaders.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Directory Changed.
        /// </summary>
        internal static string ConfigurationDirectoryChanged_Caption {
            get {
                return ResourceManager.GetString("ConfigurationDirectoryChanged_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active shader configuration directory has changed. Saving this configuration will create and store a file in the new directory. Are you sure you want to continue?.
        /// </summary>
        internal static string ConfigurationDirectoryChanged_Message {
            get {
                return ResourceManager.GetString("ConfigurationDirectoryChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete Configuration File.
        /// </summary>
        internal static string ConfigurationFileUpgrade_Caption {
            get {
                return ResourceManager.GetString("ConfigurationFileUpgrade_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current shader configuration file was created with an older version of the shaders module. Would you like to upgrade? Note: you need to upgrade in order to change any settings but this operation is non-reversible..
        /// </summary>
        internal static string ConfigurationFileUpgrade_Message {
            get {
                return ResourceManager.GetString("ConfigurationFileUpgrade_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Error.
        /// </summary>
        internal static string ConfigurationReadError_Caption {
            get {
                return ResourceManager.GetString("ConfigurationReadError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the current shader configuration file. Please make sure that the file is accessible and that it has a correct format. Detailed error message:
        ///
        ///{0}.
        /// </summary>
        internal static string ConfigurationReadError_Message {
            get {
                return ResourceManager.GetString("ConfigurationReadError_Message", resourceCulture);
            }
        }
    }
}
