//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly reference &apos;{0}&apos; has already been assigned to a different location. Consider uninstalling the conflicting package..
        /// </summary>
        internal static string AssemblyReferenceLocationMismatchException {
            get {
                return ResourceManager.GetString("AssemblyReferenceLocationMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: no bootstrapper file was found in editor package..
        /// </summary>
        internal static string BootstrapperMissingFromPackage {
            get {
                return ResourceManager.GetString("BootstrapperMissingFromPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent directory has an invalid name. The exported workflow must be placed inside a folder with the name &apos;{0}&apos;. Please rename either the parent directory or the workflow. .
        /// </summary>
        internal static string ExportPackageInvalidDirectory {
            get {
                return ResourceManager.GetString("ExportPackageInvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the existing package manifest file &apos;{0}&apos;. Please make sure that the file is accessible and that it has a correct format. Detailed error message:
        ///
        ///{1}.
        /// </summary>
        internal static string ExportPackageManifestReadError {
            get {
                return ResourceManager.GetString("ExportPackageManifestReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install editor package. Please confirm that there is an active network or local connection to the package repository. The Bonsai bootstrapper will now close..
        /// </summary>
        internal static string InstallEditorPackageError {
            get {
                return ResourceManager.GetString("InstallEditorPackageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable package.
        /// </summary>
        internal static string InstallExecutablePackageCaption {
            get {
                return ResourceManager.GetString("InstallExecutablePackageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; is an executable package. Do you want to open the workflow?.
        /// </summary>
        internal static string InstallExecutablePackageWarning {
            get {
                return ResourceManager.GetString("InstallExecutablePackageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library folder &apos;{0}&apos; has already been assigned to a different platform. Consider uninstalling the conflicting package..
        /// </summary>
        internal static string LibraryFolderPlatformMismatchException {
            get {
                return ResourceManager.GetString("LibraryFolderPlatformMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update editor package. Please confirm that there is an active network or local connection to the package repository. The Bonsai bootstrapper will now close..
        /// </summary>
        internal static string UpdateEditorPackageError {
            get {
                return ResourceManager.GetString("UpdateEditorPackageError", resourceCulture);
            }
        }
    }
}
