//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.NuGet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.NuGet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllNodeName {
            get {
                return ResourceManager.GetString("AllNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing package metadata file exists. Do you want to create a new file?.
        /// </summary>
        internal static string CreatePackageMetadata {
            get {
                return ResourceManager.GetString("CreatePackageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each item above may have sub-dependencies subject to additional license agreements..
        /// </summary>
        internal static string DependencyLicenseWarningLabel {
            get {
                return ResourceManager.GetString("DependencyLicenseWarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string ExportOperationLabel {
            get {
                return ResourceManager.GetString("ExportOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string FailedOperationLabel {
            get {
                return ResourceManager.GetString("FailedOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed packages.
        /// </summary>
        internal static string InstalledPackagesNodeName {
            get {
                return ResourceManager.GetString("InstalledPackagesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable package.
        /// </summary>
        internal static string InstallExecutablePackageCaption {
            get {
                return ResourceManager.GetString("InstallExecutablePackageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; is an executable package. Do you want to open the workflow?.
        /// </summary>
        internal static string InstallExecutablePackageWarning {
            get {
                return ResourceManager.GetString("InstallExecutablePackageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string InstallOperationLabel {
            get {
                return ResourceManager.GetString("InstallOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallOperationName {
            get {
                return ResourceManager.GetString("InstallOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos;..
        /// </summary>
        internal static string InstallPackageLatestVersion {
            get {
                return ResourceManager.GetString("InstallPackageLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0} {1}&apos;..
        /// </summary>
        internal static string InstallPackageVersion {
            get {
                return ResourceManager.GetString("InstallPackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Author: {0}).
        /// </summary>
        internal static string LicenseAuthorshipLabel {
            get {
                return ResourceManager.GetString("LicenseAuthorshipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License.
        /// </summary>
        internal static string LicenseViewLicenseLabel {
            get {
                return ResourceManager.GetString("LicenseViewLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string MissingPackageLatestVersion {
            get {
                return ResourceManager.GetString("MissingPackageLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0} {1}&apos; could not be found..
        /// </summary>
        internal static string MissingPackageVersion {
            get {
                return ResourceManager.GetString("MissingPackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open gallery package. No &apos;{0}&apos; was found in package contents..
        /// </summary>
        internal static string MissingWorkflowEntryPoint {
            get {
                return ResourceManager.GetString("MissingWorkflowEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple updates available..
        /// </summary>
        internal static string MultipleUpdatesLabel {
            get {
                return ResourceManager.GetString("MultipleUpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        internal static string MultipleUpdatesOperationName {
            get {
                return ResourceManager.GetString("MultipleUpdatesOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dependencies.
        /// </summary>
        internal static string NoDependenciesLabel {
            get {
                return ResourceManager.GetString("NoDependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        internal static string NoItemsFoundLabel {
            get {
                return ResourceManager.GetString("NoItemsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package updates are available..
        /// </summary>
        internal static string NoUpdatesAvailableLabel {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string OnlineNodeName {
            get {
                return ResourceManager.GetString("OnlineNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenOperationName {
            get {
                return ResourceManager.GetString("OpenOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already installed..
        /// </summary>
        internal static string PackageAlreadyInstalled {
            get {
                return ResourceManager.GetString("PackageAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; depends on the following packages. Do you want to uninstall them too?
        ///.
        /// </summary>
        internal static string PackageDependencyNotice {
            get {
                return ResourceManager.GetString("PackageDependencyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0} {1}&apos; exported successfully..
        /// </summary>
        internal static string PackageExported {
            get {
                return ResourceManager.GetString("PackageExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageViewNodeCheckedImage {
            get {
                object obj = ResourceManager.GetObject("PackageViewNodeCheckedImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Prerelease).
        /// </summary>
        internal static string PrereleaseLabel {
            get {
                return ResourceManager.GetString("PrereleaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring dependency &apos;{0} {1}&apos;..
        /// </summary>
        internal static string RestorePackageVersion {
            get {
                return ResourceManager.GetString("RestorePackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information....
        /// </summary>
        internal static string RetrievingInformationLabel {
            get {
                return ResourceManager.GetString("RetrievingInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &apos;{0}&apos; already exists. Please select a different folder name..
        /// </summary>
        internal static string SaveFolderExists {
            get {
                return ResourceManager.GetString("SaveFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location already exists.
        /// </summary>
        internal static string SaveFolderExistsCaption {
            get {
                return ResourceManager.GetString("SaveFolderExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package metadata has unsaved changes. Save metadata file?.
        /// </summary>
        internal static string SavePackageMetadata {
            get {
                return ResourceManager.GetString("SavePackageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Online (Ctrl+E).
        /// </summary>
        internal static string SearchOnlineCueBanner {
            get {
                return ResourceManager.GetString("SearchOnlineCueBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string UninstallOperationLabel {
            get {
                return ResourceManager.GetString("UninstallOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UninstallOperationName {
            get {
                return ResourceManager.GetString("UninstallOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unpublished).
        /// </summary>
        internal static string UnpublishedLabel {
            get {
                return ResourceManager.GetString("UnpublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string UpdateOperationLabel {
            get {
                return ResourceManager.GetString("UpdateOperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateOperationName {
            get {
                return ResourceManager.GetString("UpdateOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string UpdatesNodeName {
            get {
                return ResourceManager.GetString("UpdatesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WaitImage {
            get {
                object obj = ResourceManager.GetObject("WaitImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
