//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple elements with the specified name &apos;{0}&apos; were found in the workflow..
        /// </summary>
        internal static string Exception_AmbiguousNamedElement {
            get {
                return ResourceManager.GetString("Exception_AmbiguousNamedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator cannot be applied to input arguments when a default operand is already specified..
        /// </summary>
        internal static string Exception_BinaryOperationNotAllowed {
            get {
                return ResourceManager.GetString("Exception_BinaryOperationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indexer with matching number of arguments is defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_IndexerNotFound {
            get {
                return ResourceManager.GetString("Exception_IndexerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve the XML type &apos;{0}&apos; without a valid clr-namespace..
        /// </summary>
        internal static string Exception_InvalidTypeNamespace {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending property assignments have been found on some of the missing included workflows. Please restore the missing files and reload the workflow..
        /// </summary>
        internal static string Exception_PendingPropertyAssignment {
            get {
                return ResourceManager.GetString("Exception_PendingPropertyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property &apos;{0}&apos; was not found in the workflow. .
        /// </summary>
        internal static string Exception_PropertyNotFound {
            get {
                return ResourceManager.GetString("Exception_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow contains non-public types. Please ensure any internal operators have been fully converted or removed before saving the workflow..
        /// </summary>
        internal static string Exception_SerializingNonPublicType {
            get {
                return ResourceManager.GetString("Exception_SerializingNonPublicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow contains unspecified types. Please install any missing packages or replace the affected modules before saving the workflow..
        /// </summary>
        internal static string Exception_SerializingUnknownTypeBuilder {
            get {
                return ResourceManager.GetString("Exception_SerializingUnknownTypeBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load type &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_TypeLoadException {
            get {
                return ResourceManager.GetString("Exception_TypeLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a proxy for the unknown type &apos;{0}&apos;. Please install any missing packages or replace this operator..
        /// </summary>
        internal static string Exception_UnknownTypeBuilder {
            get {
                return ResourceManager.GetString("Exception_UnknownTypeBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported number of arguments. This node supports at most {0} input connection(s)..
        /// </summary>
        internal static string Exception_UnsupportedMaxArgumentCount {
            get {
                return ResourceManager.GetString("Exception_UnsupportedMaxArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported number of arguments. This node requires at least {0} input connection(s)..
        /// </summary>
        internal static string Exception_UnsupportedMinArgumentCount {
            get {
                return ResourceManager.GetString("Exception_UnsupportedMinArgumentCount", resourceCulture);
            }
        }
    }
}
