//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly reference &apos;{0}&apos; has already been assigned to a different location. Consider uninstalling the conflicting package..
        /// </summary>
        internal static string AssemblyReferenceLocationMismatchException {
            get {
                return ResourceManager.GetString("AssemblyReferenceLocationMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: no bootstrapper file was found in editor package..
        /// </summary>
        internal static string BootstrapperMissingFromPackage {
            get {
                return ResourceManager.GetString("BootstrapperMissingFromPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local environment bootstrapper at &apos;{0}&apos; is invalid. SHA256 checksum does not match..
        /// </summary>
        internal static string Error_InvalidBootstrapperChecksum {
            get {
                return ResourceManager.GetString("Error_InvalidBootstrapperChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bootstrapper launcher does not currently support custom command-line arguments..
        /// </summary>
        internal static string Error_InvalidCommandLineArguments {
            get {
                return ResourceManager.GetString("Error_InvalidCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SHA256 checksum for downloaded {0} is invalid..
        /// </summary>
        internal static string Error_InvalidDownloadChecksum {
            get {
                return ResourceManager.GetString("Error_InvalidDownloadChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local environment configuration found at &apos;{0}&apos; specifies a bootstrapper version {1}, which is unsupported by this launcher version {2}..
        /// </summary>
        internal static string Error_UnsupportedBootstrapperVersion {
            get {
                return ResourceManager.GetString("Error_UnsupportedBootstrapperVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install bootstrapper package. Please confirm there is an active network or local connection to the package repository..
        /// </summary>
        internal static string InstallBootstrapperPackageError {
            get {
                return ResourceManager.GetString("InstallBootstrapperPackageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library folder &apos;{0}&apos; has already been assigned to a different platform. Consider uninstalling the conflicting package..
        /// </summary>
        internal static string LibraryFolderPlatformMismatchException {
            get {
                return ResourceManager.GetString("LibraryFolderPlatformMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to restore bootstrapper package. Please confirm there is an active network or local connection to the package repository..
        /// </summary>
        internal static string UpdateBootstrapperPackageError {
            get {
                return ResourceManager.GetString("UpdateBootstrapperPackageError", resourceCulture);
            }
        }
    }
}
